apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testservice
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        run: nginx
      spec:
        containers:
        - image: gcr.io/kuar-demo/kuard-amd64:1
          imagePullPolicy: Always
        dnsPolicy: Clusterfirst
        restartPolicy: Always
