apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  spec:
    replicas: 2
    selector:
      matchLabels:
        run: nginx
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    template:
      metadata:
        labels:
          run: nginx
        spec:
          containers:
          - image: nginx:1.6
            imagePullPolicy: Always
          dnsPolicy: Clusterfirst
          restartPolicy: Always
